name: Linter Code

on:
  pull_request:
    branches :
      - dev
      - main
      
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: './app/front/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: ./app/front

    - name: Run ESLint
      run: npx eslint .
      working-directory: ./app/front

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: './app/back/requirements.txt'
    
    - name: Install & Run Ruff 
      run: |
        pip install ruff
        ruff check .
        ruff format --check
      working-directory: ./app/back