name: Security Audit

on:
  pull_request:
    branches: [ dev, main ]
  schedule:
    - cron: '15 22 * * *' # Every days at 10:15 PM

jobs:
  # Verification Front
  npm-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run NPM Audit
        run: |
          cd app/front
          npm audit --audit-level=high
      - name: Send Mail on NPM Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }} 
          password: ${{ secrets.MAIL_PASSWORD }} 
          subject: "Alerte Sécurité : Échec de l'audit Front sur GitHub Actions"
          to: admin.pfe.fly@gmail.com 
          from: GitHub Actions
          body: |
            L'analyse de sécurité sur le Front a détecté des vulnérabilités dans le code.
            Dépôt : ${{ github.repository }}
            Lien vers les logs : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

  # Verification Back
  python-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Security Tools
        run: pip install "safety<3.0" bandit
      - name: Check Dependencies (Safety)
        run: safety check -r app/back/requirements.txt
      - name: Check Code Patterns (Bandit)
        run: bandit -r app/back/ -lll 
      - name: Send Mail on Bandit Failure
        if: failure() 
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com 
          server_port: 465
          secure: true
          username: ${{ secrets.MAIL_USERNAME }} 
          password: ${{ secrets.MAIL_PASSWORD }} 
          subject: "Alerte Sécurité : Échec de l'audit Back sur GitHub Actions"
          to: admin.pfe.fly@gmail.com 
          from: GitHub Actions
          body: |
            L'analyse de sécurité sur le Back a détecté des vulnérabilités dans le code.
            Dépôt : ${{ github.repository }}
            Lien vers les logs : https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}